# Generated by Django 4.2.7 on 2025-10-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_partner_deleted_at_alter_partner_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttrColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='app.company')),
            ],
            options={
                'db_table': 'product_attr_color',
            },
        ),
        migrations.CreateModel(
            name='ProductAttrSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='app.company')),
            ],
            options={
                'db_table': 'product_attr_size',
                'indexes': [models.Index(fields=['company', 'code'], name='product_att_company_bfc6a6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productattrsize',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_size_code'),
        ),
        migrations.AddIndex(
            model_name='productattrcolor',
            index=models.Index(fields=['company', 'code'], name='product_att_company_ff6a0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattrcolor',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_color_code'),
        ),
    ]
