# Generated by Django 4.2.7 on 2025-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
