# Generated by Django 4.2.7 on 2025-10-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_partner_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_partner_ids', to='app.company'),
            preserve_default=False,
        ),
    ]
