# Generated by Django 4.2.7 on 2025-10-16 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_partner_company'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_user_ids', to='app.company'),
            preserve_default=False,
        ),
    ]
