# Generated by Django 4.2.7 on 2025-10-16 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_partner_company'),
        ('authentication', '0002_usercompany_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompany',
            new_name='AuthUserCompany',
        ),
        migrations.AlterUniqueTogether(
            name='authusercompany',
            unique_together={('user', 'company')},
        ),
        migrations.AlterModelTable(
            name='authusercompany',
            table='auth_user_company',
        ),
    ]
