# Generated by Django 4.2.7 on 2025-10-16 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_partner_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_rename_usercompany_authusercompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auth_user_company_ids', to='app.company'),
        ),
        migrations.AlterField(
            model_name='authusercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auth_user_user_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
