# Generated by Django 4.2.7 on 2025-10-16 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_partner_company'),
        ('authentication', '0004_alter_authusercompany_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authusercompany',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authusercompany',
            name='company_code',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authusercompany',
            unique_together={('user', 'company_code', 'company')},
        ),
    ]
