# Generated by Django 4.2.7 on 2025-10-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_authusercompany_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusercompany',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
