# Generated by Django 4.2.7 on 2025-10-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_partner_deleted_at_alter_partner_company'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_authusercompany_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auth_user_group_company_ids', to='app.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auth_user_group_ids', to='auth.group')),
            ],
            options={
                'db_table': 'auth_group_company',
                'unique_together': {('group', 'company_code', 'company')},
            },
        ),
    ]
