# Generated by Django 4.2.7 on 2025-10-18 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_partner_deleted_at_alter_partner_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_authgroupcompany'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authgroupcompany',
            unique_together={('group', 'company')},
        ),
        migrations.AddField(
            model_name='authgroupcompany',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='authusercompany',
            unique_together={('user', 'company')},
        ),
        migrations.RemoveField(
            model_name='authgroupcompany',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='authusercompany',
            name='company_code',
        ),
    ]
