# Generated by Django 4.2.7 on 2025-10-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='partner',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='order',
            new_name='order_id',
        ),
    ]
