# Generated by Django 4.2.7 on 2025-10-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_partner'),
        ('crm', '0002_rename_company_order_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_order_ids', to='app.partner'),
            preserve_default=False,
        ),
    ]
