# Generated by Django 4.2.7 on 2025-10-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_order_partner_id_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
