# Generated by Django 4.2.7 on 2025-10-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_company_id_order_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
    ]
