# Generated by Django 4.2.7 on 2025-10-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_order_id_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
