# Generated by Django 4.2.7 on 2025-10-10 03:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
